### ISSUE TITLE
Polling GUI should check the "bad base current" and relay state

### ISSUE THREAD

**Issue by tannerbk** [BillyLiggins/PollingGui#12]
When displaying base currents the polling gui should display channels with known bad base currents as a different color (Very similarly to what is doing with low occ, zero occ, etc channels). There exists in the channel data base a "bad base currents". 

The other thing that would be nice is if it displayed if that channel was supposed to be at high voltage or not for open relays (similar to whats done for pulled resistors). Here is a little block of code that might be helpful:
`       sql_result = conn.execute('''SELECT hv_relay_mask1, hv_relay_mask2 from  `
                                       `current_crate_state where crate = %i''' % crate)`

`sql_result = sql_result.fetchall()`

`for card in range(16):`
   `for channel in range(32):`
      `hv_relay_mask = sql_result[0][1] << 32 | sql_result[0][0]`
         `is_hv_on = hv_relay_mask & (1 << (card*4 + (3-channel//8))) `

**Comment by BillyLiggins** [comment]
This should now be in 👍
