### ISSUE TITLE
Datastream timeout needed increasing when running from CROX

### ISSUE THREAD

**Issue by estherturner** [BillyLiggins/PollingGui#13]
We have been testing all of the monitoring tools from the Oxford control room and the polling gui was one that we needed to alter a bit to make work. (I would have thought it was due to running from across the Atlantic, but obviously, you've been running it from London...)
The polling gui would let you put in the password, then fail to open (due to a timeout error when we ran from the terminal).
We solved this by increasing the timeout for the data stream from 0.05 to 0.5 on line 428 of /usr/lib/python2.6/site-packages/pollinggui.py
If you want, I can try and recreate the error, seeing as I didn't actually copy it anywhere. But with the change, it seemed to be working fine.

**Comment by BillyLiggins** [comment]
Addressed in #14 . 👍
