### ISSUE TITLE
polling gui should run in autocommit mode

### ISSUE THREAD

**Issue by tlatorre-uchicago** [BillyLiggins/PollingGui#9]
Currently, the polling gui does not run in autocommit mode, which can lock up the database for other operations.

I think this should be an easy fix, just need to add a single line after creating the connection:

```
import psycopg2
import psycopg2.extensions

conn = psycopg2.connect(...)
conn.set_isolation_level(psycopg2.extensions.ISOLATION_LEVEL_AUTOCOMMIT)
```

**Comment by tlatorre-uchicago** [comment]
Any update on this? It's now caused the database tables to be locked a couple of times.

**Comment by BillyLiggins** [comment]
Sorry Tony, I sat on this for too long. I have push up the fix you suggest and changed some of the colouring. when low gains are updated in pmtdb they will gray out as well. 

I have tested it on my laptop and it seems to work, but i don't know how to get this on to the computers in the control rooms.
